version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Mount the source code for development
      - ./:/app
      # Don't overwrite node_modules with the host's
      - /app/node_modules
      # Don't overwrite .next with the host's
      - /app/.next
    environment:
      - NODE_ENV=production
      # Add any other environment variables your app needs
    restart: unless-stopped 